apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-ingest
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}
    role: ingest
    team: {{ .Values.odfe.env.TEAM }}
spec:
  replicas: {{ .Values.ingest.replicas }}
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: ingest
      team: {{ .Values.odfe.env.TEAM }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "{{ .Values.odfe.istio.inject }}"
        traffic.sidecar.istio.io/includeInboundPorts: "*"
        traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
        traffic.sidecar.istio.io/excludeInboundPorts: "9300"
      labels:
        component: {{ template "fullname" . }}
        role: ingest
        team: {{ .Values.odfe.env.TEAM }}
        app: {{ template "fullname" . }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      {{- if eq .Values.ingest.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: ingest
      {{- else if eq .Values.ingest.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: ingest
      {{- end }}
      containers:
      - name: {{ template "fullname" . }}-ingest
        image: "{{ .Values.odfe.image.repository }}:{{ .Values.odfe.image.tag }}"
        imagePullPolicy: {{ .Values.odfe.image.pullPolicy }}
        env:
{{ if not .Values.odfe.security.enabled}}
        - name: opendistro_security.disabled
          value: "true"
 {{ end }}
 {{ if .Values.odfe.ssl.http.enabled }}
        - name: opendistro_security.ssl.http.enabled
          value: "true"
{{ end }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: discovery.seed_hosts
          value: {{ template "fullname" . }}-discovery
        {{- range $key, $value :=  .Values.odfe.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .Values.ingest.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.ingest.resources | indent 10 }}
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9600
          name: metrics
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 20
{{- if .Values.odfe.security.enabled }}
        volumeMounts:
{{ toYaml .Values.odfe.security.volumeMounts | indent 10 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ template "fullname" . }}-certs
        - name: config
          secret:
            secretName: {{ template "fullname" . }}-config
{{- end }}
