{{ if and .Values.odfe.istio.enabled .Values.virtualservice }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}
    team: {{ .Values.odfe.env.TEAM }}
spec:
  gateways:
  - istio-system/{{ .Values.virtualservice.gateway }}
  hosts:
  - {{ template "fullname" . }}-kibana.{{ .Values.virtualservice.domain }}
  http:
  - route:
    - destination:
        host: {{ template "fullname" . }}-kibana
        port:
          number: 5601
      weight: 100
{{ end }}
